### ISSUE TITLE
Leading slashes in Express routes not ignored

### ISSUE THREAD

**Issue by SNSTRUTHERS** [0cfg/0cfg-rpc#28]
## Expected Behavior
`RpcServerConfig.Builder.setExpressApp`, when adding an express app with pre-existing routes, alongside additional routers, should register all root path route names as reserved.

## Current Behavior
An express app with two routes set with as `/one` and `/two` attempts to reserve the an empty string twice, raising an error.

## Steps to Reproduce
1. Create a new express app.
2. Create two `post` listeners on the express app, with the routes `/one` and `/two` assigned to them.
3. Create a new `RpcServerConfig.Builder` via `RpcServerConfig.newBuilder()`.
4. Call `setExpressApp` on the config builder, providing the express app as a parameter.

## ~~Possible~~ Implementation
```js
const getFirstPathElement = (path: any) => path.replace(/^\//, '').split('/')[0];
```

**Comment by romfrolov** [comment]
@SNSTRUTHERS is it possible to add a route without a leading slash in the first place?
